---
- name: Install python
  apt:
    name: python3
  become: true

- name: Install pip
  apt:
    name: python3-pip
  become: true

- name: Install pipx
  pip:
    name: pipx
    state: latest
    break_system_packages: yes

- name: Install python-is-python3
  apt:
    name: python-is-python3
  become: true

