- name: Check ThreatCheck
  win_stat:
    path: "{{ ansible_user_dir }}/Desktop/ThreatCheck"
  register: folder_status

- name: Download ThreatCheck
  win_command: >
    git clone https://github.com/rasta-mouse/ThreatCheck "{{ ansible_user_dir }}\Desktop\ThreatCheck"
  when: not folder_status.stat.exists

- name: Build ThreatCheck
  win_command: >
    dotnet build ThreatCheck\ThreatCheck.csproj -c Release
  args:
    chdir: "{{ ansible_user_dir }}\\Desktop\\ThreatCheck"
