---
- hosts: "{{target|default('all')}}"
  vars:
    rust_env:
      PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"
      CARGO_HOME: "{{ ansible_user_dir }}/.cargo"
      RUSTUP_HOME: "{{ ansible_user_dir }}/.rustup"
  roles:
   - role: apt_upgrade
     tags: apt_upgrade
   - role: cdev
     tags: cdev
   - role: tools_dir
     tags: tools_dir
   - role: firefox
     tags: firefox
   - role: cargo
     tags: cargo
   - role: golang
     tags: golang
   - role: python
     tags: python
   - role: gping
     tags: gping
   - role: jre
     tags: jre
   - role: duf
     tags: duf
   - role: dust
     tags: dust
   - role: ufw
     tags: ufw
   - role: openvpn
     tags: openvpn
   - role: nordvpn
     tags: nordvpn
   - role: docker
     tags: docker
   - role: tcpdump
     tags: tcpdump
   - role: wireshark
     tags: wireshark
   - role: gdb
     tags: gdb
   - role: sublime
     tags: sublime
   - role: tcptraceroute
     tags: tcptraceroute
   - role: drawio
     tags: drawio
   - role: btop  
     tags: btop  
   - role: dashboard
     tags: dashboard
   - role: gpg
     tags: gpg
   - role: bat
     tags: bat
   - role: locate
     tags: locate
   - role: xclip
     tags: xclip
   - role: net-tools
     tags: net-tools
   - role: hextools
     tags: hextools
   - role: diceware
     tags: diceware
   - role: delta
     tags: delta
   - role: curlie
     tags: curlie
