
https://github.com/dobin/avred-server
nssm.exe install AvredServer
nssm.exe set AvredServer Application "C:\Users\hacker\AppData\Local\Programs\Python\Python310\python.exe"
nssm.exe set AvredServer AppDirectory "C:\Users\hacker\Desktop\avred-server\"
nssm.exe set AvredServer AppParameters "C:\Users\hacker\Desktop\avred-server\avred_server.py"
nssm.exe start AvredServer


https://github.com/dobin/avred
pip3 install --upgrade -r requirements.txt

https://community.chocolatey.org/packages/radare2

$ podman build -t avred .