---
- hosts: "{{target|default('all')}}"
  roles:
   - role: detect_it_easy
     tags: detect_it_easy
   - role: ghidra
     tags: ghidra
   - role: pebear
     tags: pebear
   - role: threatcheck
     tags: threatcheck