---
- hosts: "{{target|default('all')}}"
  roles:
   - role: tools_dir
     tags: tools_dir
   - role: nmap
     tags: nmap
   - role: cutter
     tags: cutter
   - role: rr
     tags: rr
   - role: hashcat
     tags: hashcat
   - role: johnj
     tags: johnj
   - role: pwntools
     tags: pwntools
   - role: impacket
     tags: impacket
   - role: nullinux
     tags: nullinux
   - role: nxc
     tags: nxc
   - role: project_discovery
     tags: project_discovery
   - role: amass
     tags: amass
   - role: wordlists
     tags: wordlists 
   - role: burpsuite
     tags: burpsuite 