- name: disable Ctrl alt delete unlock requirement
  when: result.changed
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DisableCAD
    data: 1
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat

# HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon]
# -name: DisableCAD"=-

# HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
# -name: DisableCAD"=-

# HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System]
# -name: DisableCAD"=-