---
- name: set dark GTK theme
  command: |
    echo "[Settings]" > {{ ansible_user_dir }}/.config/gtk-3.0/settings.ini
    echo "gtk-application-prefer-dark-theme=1" >> {{ ansible_user_dir }}/.config/gtk-3.0/settings.ini

