---
- name: x11-xserver-utils_apt
  ansible.builtin.apt:
    name: x11-xserver-utils
    state: latest
  become: true
- name: arandr_apt
  ansible.builtin.apt:
    name: arandr
    state: latest
  become: true
- name: autorandr_apt
  ansible.builtin.apt:
    name: autorandr
    state: latest
  become: true