---
- name: dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/jrhenderson11/dotfiles'
    dest: "{{ ansible_user_dir }}/tools/dotfiles"

 - name: Link aliases
    ansible.builtin.file:
      src: "{{ ansible_user_dir }}/tools/dotfiles/.aliases"
      dest: "{{ ansible_user_dir }}/.aliases"
      state: link

 - name: Link i3 config
    ansible.builtin.file:
      src: "{{ ansible_user_dir }}/tools/dotfiles/i3"
      dest: "{{ ansible_user_dir }}/.config/i3"
      state: link

 - name: Link .gitconfig
    ansible.builtin.file:
      src: "{{ ansible_user_dir }}/tools/dotfiles/.gitconfig"
      dest: "{{ ansible_user_dir }}/.gitconfig"
      state: link
 - name: Link .gitconfig-priv
    ansible.builtin.file:
      src: "{{ ansible_user_dir }}/tools/dotfiles/.gitconfig-priv"
      dest: "{{ ansible_user_dir }}/.gitconfig-priv"
      state: link
 - name: Link .gitconfig-work
    ansible.builtin.file:
      src: "{{ ansible_user_dir }}/tools/dotfiles/.gitconfig-work"
      dest: "{{ ansible_user_dir }}/.gitconfig-work"
      state: link

# IF LAPTOP
# ln $PWD/.inputrc ~/.inputrc

# # Use pactl to adjust volume in PulseAudio.
# set $refresh_i3status killall -SIGUSR1 i3status
# bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
# bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
# bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
# bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status
